on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight every day
  push:
    branches: [ main ]   # Also runs whenever you push to main branch
  workflow_dispatch:     # Allows manual triggering from GitHub UI

jobs:
  update-payments:
    runs-on: ubuntu-latest
    steps:
      - name: Call Edge Function
        run: |
          curl -X POST "https://cwsxmkwgocgpbuyiafzc.supabase.co/functions/v1/update-overdue-payments" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Content-Type: application/json"
      
      - name: Check Response
        run: |
          echo "Edge Function called successfully. Check Supabase logs for details."
